- hosts: all
  remote_user: ubuntu
  become: true
  gather_facts: yes


  vars:
      stack_version: 7.9.2
      ubuntu_version: bionic


  pre_tasks:
    - name: Install Python2 to make Ansible work
      raw: sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get -y install python2-minimal


  tasks:

    - name: Update and upgrade apt packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Change the mmap to a reasonable size
      shell: sysctl -w vm.max_map_count=262144

    - name: Install some developer tools
      apt:
        name:
          - ntp
          - ntpdate
          - python3-pip
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - whois
        force_apt_get: yes

    - name: Install Ansible dependencies
      pip:
        name: docker

    - name: Install Docker's fingerprint
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install Docker's repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version }} stable
        state: present

    - name: Install Docker's binaries
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - docker-compose
        force_apt_get: yes

    - name: Start and enable the Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Fetch the Elastic Docker images for later use
      docker_image:
        name: "{{ item }}"
        source: pull
      with_items:
        - "docker.elastic.co/elasticsearch/elasticsearch:{{ stack_version }}"
        - "docker.elastic.co/kibana/kibana:{{ stack_version }}"
        - "docker.elastic.co/beats/metricbeat:{{ stack_version }}"

    - name: Create a directory for the demo
      file:
        path: /opt/scale-elasticsearch/
        state: directory
        mode: '0755'

    - name: Provide the Metricbeat configuration
      copy:
        src: metricbeat/
        dest: /opt/scale-elasticsearch/metricbeat/
        mode: '0755'

    - name: Provide the setup
      copy:
        src: setup/
        dest: /opt/scale-elasticsearch/setup/
        mode: '0755'

    - name: Provide the Docker configuration
      copy: "src={{ item }} dest=/opt/scale-elasticsearch/ mode='0755'"
      loop:
        - .env
        - docker-compose.yml
        - Dockerfile
        - kibana.yml
